import type { Bank } from "./bank.model";

export const BANKS: Bank[] = [
  {
    name: "Swedbank",
    website: "https://www.swedbank.se",
    providesBankId: true,
    providesSwish: true,
    studentFriendly: true,
    englishSupport: true,
    debitCard: true,
    creditCard: true,
    applePay: true,
    googleWallet: true,
    samsungWallet: false,
    physicalBranches: true,
    mobileApp: true,
    accountWithoutPersonnummer: true,
    businessAccounts: true,
    fee: "Free / Varies",
    notes: "One of Sweden's largest banks with excellent newcomer support.",
  },
  {
    name: "SEB",
    website: "https://seb.se",
    providesBankId: true,
    providesSwish: true,
    studentFriendly: true,
    englishSupport: true,
    debitCard: true,
    creditCard: true,
    applePay: true,
    googleWallet: true,
    samsungWallet: false,
    physicalBranches: true,
    mobileApp: true,
    accountWithoutPersonnummer: true,
    businessAccounts: true,
    fee: "Free / Varies",
    notes: "Popular with professionals and international customers.",
  },
  {
    name: "Nordea",
    website: "https://www.nordea.se",
    providesBankId: true,
    providesSwish: true,
    studentFriendly: true,
    englishSupport: true,
    debitCard: true,
    creditCard: true,
    applePay: true,
    googleWallet: true,
    samsungWallet: true,
    physicalBranches: true,
    mobileApp: true,
    accountWithoutPersonnummer: true,
    businessAccounts: true,
    fee: "Free / Varies",
    notes: "Large Nordic bank with strong mobile banking.",
  },
  {
    name: "Handelsbanken",
    website: "https://www.handelsbanken.se",
    providesBankId: true,
    providesSwish: true,
    studentFriendly: true,
    englishSupport: true,
    debitCard: true,
    creditCard: true,
    applePay: true,
    googleWallet: true,
    samsungWallet: false,
    physicalBranches: true,
    mobileApp: true,
    accountWithoutPersonnummer: true,
    businessAccounts: true,
    fee: "Varies",
    notes: "Well known for personal customer service.",
  },
  {
    name: "ICA Banken",
    website: "https://www.icabanken.se",
    providesBankId: true,
    providesSwish: true,
    studentFriendly: false,
    englishSupport: true,
    debitCard: true,
    creditCard: true,
    applePay: true,
    googleWallet: true,
    samsungWallet: false,
    physicalBranches: false,
    mobileApp: true,
    accountWithoutPersonnummer: false,
    businessAccounts: false,
    fee: "Varies",
    notes: "Convenient if you shop regularly at ICA.",
  },
  {
    name: "Lansforsakringar Bank",
    website: "https://www.lansforsakringar.se",
    providesBankId: true,
    providesSwish: true,
    studentFriendly: true,
    englishSupport: true,
    debitCard: true,
    creditCard: true,
    applePay: true,
    googleWallet: true,
    samsungWallet: false,
    physicalBranches: true,
    mobileApp: true,
    accountWithoutPersonnummer: true,
    businessAccounts: true,
    fee: "Varies",
    notes: "Good option if you also need insurance.",
  },
  {
    name: "Skandia",
    website: "https://www.skandia.se",
    providesBankId: true,
    providesSwish: true,
    studentFriendly: false,
    englishSupport: true,
    debitCard: true,
    creditCard: true,
    applePay: true,
    googleWallet: true,
    samsungWallet: false,
    physicalBranches: false,
    mobileApp: true,
    accountWithoutPersonnummer: false,
    businessAccounts: true,
    fee: "Varies",
    notes: "Strong digital banking experience.",
  },
  {
    name: "Danske Bank Sweden",
    website: "https://danskebank.se",
    providesBankId: true,
    providesSwish: true,
    studentFriendly: false,
    englishSupport: true,
    debitCard: true,
    creditCard: true,
    applePay: true,
    googleWallet: true,
    samsungWallet: false,
    physicalBranches: true,
    mobileApp: true,
    accountWithoutPersonnummer: false,
    businessAccounts: true,
    fee: "Varies",
    notes: "Good cross-border banking for Nordic customers.",
  },
  {
    name: "Revolut",
    website: "https://www.revolut.com",
    providesBankId: false,
    providesSwish: false,
    studentFriendly: true,
    englishSupport: true,
    debitCard: true,
    creditCard: false,
    applePay: true,
    googleWallet: true,
    samsungWallet: true,
    physicalBranches: false,
    mobileApp: true,
    accountWithoutPersonnummer: true,
    businessAccounts: true,
    fee: "Free / Paid Plans",
    notes:
      "Excellent for travel and international transfers but not a replacement for a Swedish bank.",
  },
  {
    name: "N26",
    website: "https://n26.com",
    providesBankId: false,
    providesSwish: false,
    studentFriendly: true,
    englishSupport: true,
    debitCard: true,
    creditCard: false,
    applePay: true,
    googleWallet: true,
    samsungWallet: true,
    physicalBranches: false,
    mobileApp: true,
    accountWithoutPersonnummer: true,
    businessAccounts: true,
    fee: "Free / Paid Plans",
    notes: "Digital bank focused on European customers.",
  },
  {
    name: "Wise",
    website: "https://wise.com",
    providesBankId: false,
    providesSwish: false,
    studentFriendly: true,
    englishSupport: true,
    debitCard: true,
    creditCard: false,
    applePay: true,
    googleWallet: true,
    samsungWallet: true,
    physicalBranches: false,
    mobileApp: true,
    accountWithoutPersonnummer: true,
    businessAccounts: true,
    fee: "Pay Per Transfer",
    notes: "Best for international transfers and holding multiple currencies.",
  },
];
